import logging
import os
from datetime import datetime

import httpx

logger = logging.getLogger(__name__)

CATEGORY_EMOJI: dict[str, str] = {
    "Sweden": "\U0001f1f8\U0001f1ea",
    "Tech": "\U0001f4bb",
    "Economy": "\U0001f4b0",
}
DEFAULT_EMOJI = "\U0001f4f0"


def _format_article_text(article: dict) -> str:
    summary = article.get("ai_summary") or article.get("summary") or ""
    if len(summary) > 300:
        summary = summary[:297] + "..."
    return f"\u2022 *{article['title']}* \u2014 {summary} <{article['url']}|Read more \u2192>"


def build_slack_blocks(digest: dict) -> list[dict]:
    now = datetime.now()
    total = sum(len(items) for items in digest["categories"].values())
    header_text = f"\U0001f4f0 News Digest \u2013 {now.strftime('%A %B %d')} \u00b7 {total} articles"
    if len(header_text) > 150:
        header_text = header_text[:150]

    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": header_text}},
    ]

    for category, items in digest["categories"].items():
        emoji = CATEGORY_EMOJI.get(category, DEFAULT_EMOJI)
        lines = [f"{emoji} *{category}*\n"]
        for article in items:
            lines.append(_format_article_text(article))
        text = "\n".join(lines)

        blocks.append({"type": "divider"})
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": text},
        })

    sources = sorted({
        a["source_name"]
        for items in digest["categories"].values()
        for a in items
    })
    footer = f"Generated by Claude \u00b7 {', '.join(sources)}"
    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn", "text": footer}],
    })

    if len(blocks) > 50:
        blocks = blocks[:49]
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "\u2026 truncated"}],
        })

    return blocks


def publish_to_slack(digest: dict) -> bool:
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        logger.warning("SLACK_WEBHOOK_URL not set, skipping Slack delivery")
        return False

    blocks = build_slack_blocks(digest)

    try:
        response = httpx.post(webhook_url, json={"blocks": blocks}, timeout=10)
        response.raise_for_status()
        logger.info("Slack message delivered successfully")
        return True
    except httpx.HTTPStatusError as e:
        logger.error(f"Slack webhook returned {e.response.status_code}: {e.response.text}")
        return False
    except httpx.RequestError as e:
        logger.error(f"Slack webhook request failed: {e}")
        return False
