import logging
import os
from datetime import datetime

import httpx
import resend

logger = logging.getLogger(__name__)

CATEGORY_EMOJI: dict[str, str] = {
    "Sweden": "\U0001f1f8\U0001f1ea",
    "Tech": "\U0001f4bb",
    "Economy": "\U0001f4b0",
}
DEFAULT_EMOJI = "\U0001f4f0"


def _format_article_text(article: dict) -> str:
    summary = article.get("ai_summary") or article.get("summary") or ""
    if len(summary) > 300:
        summary = summary[:297] + "..."
    return f"\u2022 *{article['title']}* \u2014 {summary} <{article['url']}|Read more \u2192>"


def build_slack_blocks(digest: dict) -> list[dict]:
    now = datetime.now()
    total = sum(len(items) for items in digest["categories"].values())
    header_text = f"\U0001f4f0 News Digest \u2013 {now.strftime('%A %B %d')} \u00b7 {total} articles"
    if len(header_text) > 150:
        header_text = header_text[:150]

    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": header_text}},
    ]

    for category, items in digest["categories"].items():
        emoji = CATEGORY_EMOJI.get(category, DEFAULT_EMOJI)
        lines = [f"{emoji} *{category}*\n"]
        for article in items:
            lines.append(_format_article_text(article))
        text = "\n".join(lines)

        blocks.append({"type": "divider"})
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": text},
        })

    sources = sorted({
        a["source_name"]
        for items in digest["categories"].values()
        for a in items
    })
    footer = f"Generated by Claude \u00b7 {', '.join(sources)}"
    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn", "text": footer}],
    })

    if len(blocks) > 50:
        blocks = blocks[:49]
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "\u2026 truncated"}],
        })

    return blocks


def publish_to_slack(digest: dict, webhook_url: str | None = None) -> bool:
    webhook_url = webhook_url or os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        logger.warning("No Slack webhook URL provided, skipping Slack delivery")
        return False

    blocks = build_slack_blocks(digest)

    try:
        response = httpx.post(webhook_url, json={"blocks": blocks}, timeout=10)
        response.raise_for_status()
        logger.info("Slack message delivered successfully")
        return True
    except httpx.HTTPStatusError as e:
        logger.error(f"Slack webhook returned {e.response.status_code}: {e.response.text}")
        return False
    except httpx.RequestError as e:
        logger.error(f"Slack webhook request failed: {e}")
        return False


def build_email_html(digest: dict) -> str:
    today = datetime.now().strftime("%A %B %d")
    total = sum(len(items) for items in digest["categories"].values())

    parts = [
        "<html><body style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 16px;\">",
        f"<h1 style=\"font-size: 22px; border-bottom: 2px solid #333; padding-bottom: 8px;\">News Digest &ndash; {today} &middot; {total} articles</h1>",
    ]

    for category, items in digest["categories"].items():
        emoji = CATEGORY_EMOJI.get(category, DEFAULT_EMOJI)
        parts.append(f"<h2 style=\"font-size: 18px; margin-top: 24px;\">{emoji} {category}</h2>")
        parts.append("<ul style=\"padding-left: 20px;\">")
        for article in items:
            summary = article.get("ai_summary") or article.get("summary") or ""
            if len(summary) > 300:
                summary = summary[:297] + "..."
            parts.append(
                f"<li style=\"margin-bottom: 12px;\">"
                f"<a href=\"{article['url']}\" style=\"font-weight: bold; color: #1a73e8; text-decoration: none;\">{article['title']}</a>"
                f"<br><span style=\"color: #555; font-size: 14px;\">{summary}</span>"
                f"</li>"
            )
        parts.append("</ul>")

    sources = sorted({
        a["source_name"]
        for items in digest["categories"].values()
        for a in items
    })
    parts.append(f"<p style=\"color: #888; font-size: 12px; margin-top: 24px; border-top: 1px solid #ddd; padding-top: 8px;\">Generated by Claude &middot; {', '.join(sources)}</p>")
    parts.append("</body></html>")

    return "\n".join(parts)


def send_email(digest: dict, to_email: str) -> bool:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        logger.warning("RESEND_API_KEY not set, skipping email delivery")
        return False

    resend.api_key = api_key
    today = datetime.now().strftime("%B %d")
    html = build_email_html(digest)
    from_email = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")

    try:
        resend.Emails.send({
            "from": from_email,
            "to": to_email,
            "subject": f"Your News Digest \u2013 {today}",
            "html": html,
        })
        logger.info(f"Email delivered to {to_email}")
        return True
    except Exception as e:
        logger.error(f"Email delivery failed for {to_email}: {e}")
        return False
